
import "https://deno.land/x/xhr@0.1.0/mod.ts";
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
import { Resend } from 'https://esm.sh/resend@4.0.0';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

// Initialize Supabase client
const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const supabase = createClient(supabaseUrl, supabaseServiceKey);

// Initialize Resend
const resend = new Resend(Deno.env.get('RESEND_API_KEY'));

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    // Check total leads count
    const { data: leads, error } = await supabase
      .from('leads')
      .select('id, created_at, email, industry')
      .order('created_at', { ascending: false });

    if (error) {
      throw error;
    }

    const totalLeads = leads?.length || 0;
    const recentLeads = leads?.slice(0, 10) || [];

    // Check if we should send notification for first 100 leads milestone
    const shouldNotify = totalLeads >= 100;

    if (shouldNotify) {
      // Send email notification
      const emailContent = `
        <h1>🎯 Lead Generation Milestone Reached!</h1>
        <p>Your AGI system has successfully generated <strong>${totalLeads} leads</strong>!</p>
        
        <h2>📊 Recent Leads Summary:</h2>
        <ul>
          ${recentLeads.map(lead => `
            <li><strong>${lead.email}</strong> - ${lead.industry || 'General'} (${new Date(lead.created_at).toLocaleString()})</li>
          `).join('')}
        </ul>
        
        <h2>💰 Revenue Potential:</h2>
        <p>Estimated revenue potential: <strong>$${(totalLeads * 500).toLocaleString()}</strong></p>
        
        <h2>🚀 Next Steps:</h2>
        <ul>
          <li>Review leads in your dashboard</li>
          <li>Launch targeted email campaigns</li>
          <li>Set up follow-up sequences</li>
          <li>Monitor conversion rates</li>
        </ul>
        
        <p>Your AGI lead generation system is working! 🤖✨</p>
      `;

      const { data: emailResult, error: emailError } = await resend.emails.send({
        from: 'AGI Lead System <onboarding@resend.dev>',
        to: ['mostafamonier13@gmail.com'],
        subject: `🎯 Milestone: ${totalLeads} Leads Generated by Your AGI System!`,
        html: emailContent
      });

      if (emailError) {
        console.error('Email sending error:', emailError);
      } else {
        console.log('Notification email sent successfully:', emailResult);
      }
    }

    return new Response(
      JSON.stringify({
        success: true,
        totalLeads,
        shouldNotify,
        message: shouldNotify ? 'Notification sent!' : 'Monitoring leads...',
        data: {
          totalLeads,
          recentLeads: recentLeads.length,
          estimatedRevenue: totalLeads * 500
        }
      }),
      { 
        headers: { 
          ...corsHeaders, 
          'Content-Type': 'application/json' 
        } 
      }
    );

  } catch (error) {
    console.error('Lead notification error:', error);
    
    return new Response(
      JSON.stringify({
        success: false,
        message: `Notification error: ${error.message}`,
        error: error.message
      }),
      { 
        status: 500,
        headers: { 
          ...corsHeaders, 
          'Content-Type': 'application/json' 
        } 
      }
    );
  }
});
